plugins:
    - serverless-plugin-typescript
    - serverless-offline

service: node-typescript-serverless

custom:
    serverlessPluginTypescript:
        tsConfigFileLocation: "./tsconfig.json"
    serverless-offline:
        noPrependStageInUrl: true
        httpPort: 3000
        host: 0.0.0.0

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-east-1

functions:
    get-docs:
        handler: src/server.handler
        events:
            - http:
                  path: /api-docs/*
                  method: get
    get-one-cat:
        handler: src/server.handler
        events:
            - http:
                  path: /cat/{id}
                  method: get
    create-cat:
        handler: src/server.handler
        events:
            - http:
                  path: /cat
                  method: post
    update-cat:
        handler: src/server.handler
        events:
            - http:
                  path: /cat/{id}
                  method: put
    remove-cat:
        handler: src/server.handler
        events:
            - http:
                  path: /cat/{id}
                  method: delete

    swagger:
        handler: src/server.handler
        events:
            - http:
                  path: /swagger/get
                  method: get
