/* tslint:disable */
/* eslint-disable */
/**
 * serverless-http-tsoa-test-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOne404Response
 */
export interface GetOne404Response {
    /**
     * 
     * @type {string}
     * @memberof GetOne404Response
     */
    reason: string;
}

/**
 * Check if a given object implements the GetOne404Response interface.
 */
export function instanceOfGetOne404Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function GetOne404ResponseFromJSON(json: any): GetOne404Response {
    return GetOne404ResponseFromJSONTyped(json, false);
}

export function GetOne404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOne404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function GetOne404ResponseToJSON(value?: GetOne404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': value.reason,
    };
}

