/* tslint:disable */
/* eslint-disable */
/**
 * serverless-http-test-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cat
 */
export interface Cat {
    /**
     * 
     * @type {string}
     * @memberof Cat
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Cat
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof Cat
     */
    breed: string;
    /**
     * 
     * @type {string}
     * @memberof Cat
     */
    id: string;
}

/**
 * Check if a given object implements the Cat interface.
 */
export function instanceOfCat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "breed" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CatFromJSON(json: any): Cat {
    return CatFromJSONTyped(json, false);
}

export function CatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'age': json['age'],
        'breed': json['breed'],
        'id': json['id'],
    };
}

export function CatToJSON(value?: Cat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'age': value.age,
        'breed': value.breed,
        'id': value.id,
    };
}

