version: "2"

services:
    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"

    api:
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        expose:
            - 3000

    test-runner:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - api
            - redis
        environment:
            - WAIT_HOSTS=api:3000
            - WAIT_TIMEOUT=60
        # volumes:
        #     - type: bind
        #       source: $PWD/../clients
        #       target: /some-client
